// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type User struct {
	Username sql.NullString `json:"username"`
	Password sql.NullString `json:"password"`
}
